-- Create test users with proper defaults
INSERT INTO auth.users (
    id,
    instance_id,
    email,
    encrypted_password,
    email_confirmed_at,
    role,
    raw_user_meta_data,
    raw_app_meta_data,
    aud,
    created_at,
    updated_at,
    confirmation_token,
    recovery_token,
    email_change_token_new,
    email_change_token_current,
    reauthentication_token,
    phone_change_token,
    is_sso_user,
    is_anonymous
) VALUES
-- Admin user
(
    'a9b8c7d6-e5f4-4a3b-8c9d-1a2b3c4d5e6f',
    (SELECT id FROM auth.instances LIMIT 1),
    'admin@test.com',
    crypt('password123', gen_salt('bf')),
    now(),
    'authenticated',
    '{"role": "admin", "full_name": "Admin User"}'::jsonb,
    '{"provider": "email", "providers": ["email"]}'::jsonb,
    'authenticated',
    now(),
    now(),
    '',
    '',
    '',
    '',
    '',
    '',
    false,
    false
),
-- Worker users
(
    '8f9c55da-5c13-4f28-9e4e-74a8c1834875',
    (SELECT id FROM auth.instances LIMIT 1),
    'worker@test.com',
    crypt('password123', gen_salt('bf')),
    now(),
    'authenticated',
    '{"role": "worker", "full_name": "Alice Worker"}'::jsonb,
    '{"provider": "email", "providers": ["email"]}'::jsonb,
    'authenticated',
    now(),
    now(),
    '',
    '',
    '',
    '',
    '',
    '',
    false,
    false
),
(
    'b4c45d3a-7d2f-4b6c-9f24-60d0f6e7d723',
    (SELECT id FROM auth.instances LIMIT 1),
    'worker2@test.com',
    crypt('password123', gen_salt('bf')),
    now(),
    'authenticated',
    '{"role": "worker", "full_name": "Bob Worker"}'::jsonb,
    '{"provider": "email", "providers": ["email"]}'::jsonb,
    'authenticated',
    now(),
    now(),
    '',
    '',
    '',
    '',
    '',
    '',
    false,
    false
),
-- Customer users
(
    'e5c6cf84-9c3d-4b63-8a7c-32d7c2941e12',
    (SELECT id FROM auth.instances LIMIT 1),
    'customer@test.com',
    crypt('password123', gen_salt('bf')),
    now(),
    'authenticated',
    '{"role": "customer", "full_name": "Charlie Customer"}'::jsonb,
    '{"provider": "email", "providers": ["email"]}'::jsonb,
    'authenticated',
    now(),
    now(),
    '',
    '',
    '',
    '',
    '',
    '',
    false,
    false
),
(
    'f7d8e9a2-6b5c-4f3d-8e9f-1a2b3c4d5e6f',
    (SELECT id FROM auth.instances LIMIT 1),
    'customer2@test.com',
    crypt('password123', gen_salt('bf')),
    now(),
    'authenticated',
    '{"role": "customer", "full_name": "Diana Customer"}'::jsonb,
    '{"provider": "email", "providers": ["email"]}'::jsonb,
    'authenticated',
    now(),
    now(),
    '',
    '',
    '',
    '',
    '',
    '',
    false,
    false
);
